# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https//github.com/CocoaPods/Specs.git'
target 'starWarsCollections' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for starWarsCollections
pod 'Alamofire', '~> 3.3' 
pod 'SwiftyJSON', '~> 2.3'
end
